# Generated by Django 6.0.4 on 2026-04-19 21:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("customers", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="LoyaltyCampaign",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=150)),
                ("description", models.TextField(blank=True)),
                ("required_purchases", models.PositiveIntegerField(default=10)),
                ("reward_name", models.CharField(max_length=150)),
                ("reward_description", models.TextField(blank=True)),
                ("reward_image", models.FileField(blank=True, upload_to="rewards/")),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Campanha de fidelidade",
                "verbose_name_plural": "Campanhas de fidelidade",
            },
        ),
        migrations.CreateModel(
            name="ThemePreset",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("primary_color", models.CharField(max_length=7)),
                ("secondary_color", models.CharField(max_length=7)),
                ("css_class", models.CharField(max_length=100, unique=True)),
                ("is_active", models.BooleanField(default=True)),
            ],
            options={
                "verbose_name": "Tema",
                "verbose_name_plural": "Temas",
            },
        ),
        migrations.CreateModel(
            name="RewardRedemption",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("redeemed_at", models.DateTimeField(auto_now_add=True)),
                ("notes", models.TextField(blank=True)),
                (
                    "campaign",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reward_redemptions",
                        to="loyalty.loyaltycampaign",
                    ),
                ),
                (
                    "customer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reward_redemptions",
                        to="customers.customer",
                    ),
                ),
            ],
            options={
                "verbose_name": "Resgate",
                "verbose_name_plural": "Resgates",
                "ordering": ["-redeemed_at"],
            },
        ),
    ]
