# Generated by Django 6.0.4 on 2026-04-19 21:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("customers", "0001_initial"),
        ("loyalty", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="purchaserecord",
            name="campaign",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="purchase_records",
                to="loyalty.loyaltycampaign",
            ),
        ),
        migrations.AddField(
            model_name="purchaserecord",
            name="customer",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="purchase_records",
                to="customers.customer",
            ),
        ),
    ]
