# Generated by Django 6.0.4 on 2026-04-19 21:20

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="CompanySettings",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(max_length=150, verbose_name="Nome da empresa"),
                ),
                ("logo", models.FileField(blank=True, upload_to="company/logos/")),
                ("banner", models.FileField(blank=True, upload_to="company/banners/")),
                ("primary_color", models.CharField(default="#1D4ED8", max_length=7)),
                ("secondary_color", models.CharField(default="#0F172A", max_length=7)),
                (
                    "theme",
                    models.CharField(
                        choices=[
                            ("classic", "Clássico"),
                            ("sunset", "Sunset"),
                            ("forest", "Forest"),
                        ],
                        default="classic",
                        max_length=20,
                    ),
                ),
                ("description", models.TextField(blank=True, verbose_name="Descrição")),
                (
                    "phone",
                    models.CharField(
                        blank=True, max_length=20, verbose_name="Telefone"
                    ),
                ),
                (
                    "address",
                    models.CharField(
                        blank=True, max_length=255, verbose_name="Endereço"
                    ),
                ),
                ("instagram", models.CharField(blank=True, max_length=255)),
                ("whatsapp", models.CharField(blank=True, max_length=20)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Configuração da empresa",
                "verbose_name_plural": "Configuração da empresa",
            },
        ),
    ]
